#!/bin/bash

# vi mode in bash
set -o vi

# include local bin path
export PATH="$PATH":/usr/local/bin

# default editor
export EDITOR=nvim
export TERM=screen-256color

# alias
alias ll='ls -alh'
alias vi='nvim'
alias vim='nvim'
alias view='nvim -R'

# tmux
mkdir -p "$HOME"/.tmux/log

# virtualenv configuration
export WORKON_HOME="$HOME"/.virtualenvs
. "$HOME"/.local/bin/virtualenvwrapper.sh

# dev
export DEV_ROOT_PATH=$HOME/git

# golang
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
source "$HOME"/.gvm/scripts/gvm
gvm use go1.10 > /dev/null
export GOPATH="$HOME"/.go
export PATH="$PATH":"$GOPATH"/bin
export PATH="$PATH":/usr/local/go/bin

# ghq
export GHQ_ROOT="$HOME"/.ghq
export GHQ_ROOT="$GHQ_ROOT":"$GOPATH"/src

# fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# locale
export LC_ALL=C

# git completion and git prompt
[[ -s "$HOME/.git-completion.bash" ]] && source "$HOME/.git-completion.bash"
[[ -s "$HOME/.git-prompt.sh" ]] && source "$HOME/.git-prompt.sh"
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUPSTREAM=auto
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\u\[\033[00m\]:\[\033[01;34m\]\w$(__git_ps1 " (%s)")\[\033[00m\]\$ '
