#!/bin/bash

# vi mode in bash
set -o vi

# include local bin path
export PATH="$PATH":/usr/local/bin

# default editor
export EDITOR=nvim
export TERM=screen-256color
# export TERM=xterm-256color

# alias
alias ls='ls --color=none'
alias grep='grep --color=none'
alias egrep='egrep --color=none'
alias fgrep='fgrep --color=none'
alias view='nvim -R'

# tmux
mkdir -p "$HOME"/.tmux/log

# virtualenv configuration
export WORKON_HOME="$HOME"/.virtualenvs
. "$HOME"/.local/bin/virtualenvwrapper.sh

# dev
mkdir -p "$HOME"/Developments

# golang
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
source "$HOME"/.gvm/scripts/gvm
gvm use go1.10 > /dev/null
export GOPATH="$HOME"/Developments/go
export PATH="$PATH":"$GOPATH"/bin
export PATH="$PATH":/usr/local/go/bin

# fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# locale
export LC_ALL=C

# git completion and git prompt
[[ -s "$HOME/.git-completion.bash" ]] && source "$HOME/.git-completion.bash"
[[ -s "$HOME/.git-prompt.sh" ]] && source "$HOME/.git-prompt.sh"
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUPSTREAM=auto
# GIT_PS1_SHOWCOLORHINTS=true
# PS1='${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\u\[\033[00m\]:\[\033[01;34m\]\w$(__git_ps1 " (%s)")\[\033[00m\]\$ '
# export PS1='\u:\w$(__git_ps1 " (%s)")\$ '
export PROMPT_COMMAND='__git_ps1 "\[\033[01;34m\]\u\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]" "\\\$ "'

JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
